NCKH-AHG/PythonWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('baitap/', include('baitap.urls'))
]
handler404 = 'home.views.error'

NCKH-AHG/home/urls.py
from django.urls import path
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
   path('', views.index, name='index'),
   path('profile/', views.profile, name='profile'),
   path('contact/', views.contact, name='contact'),
   path('register', views.register, name="register"),
   path('login/',auth_views.LoginView.as_view(template_name="pages/login.html"), name="login"),
   path('logout/',auth_views.LogoutView.as_view(next_page='/'),name='logout'),
   path('nopbai/', views.nopbai, name='nopbai'),
   path('update/', views.add_profile, name='addprofile'),
   path('updateprofile/', views.update_profile, name='updateprofile'),
   path('rolegv/', views.rolegv, name='rolegv'),
   path('roleselect/', views.roleselect, name='roleselect'),
]

NCKH-AHG/home/models.py
from django.db import models

NCKH-AHG/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
# Create your models here.

class CustomerUser(AbstractUser):
    uid = models.AutoField(primary_key=True)
    role_choice = ((0, "Students"), (1, "Teachers"))
    lop = models.CharField(max_length=20, blank=True, null=True)
    school = models.CharField(max_length=30)
    phone_number = models.CharField(default=0, max_length=15)
    subject = models.CharField(max_length=20, default='History') 
    stt = models.IntegerField(default=0)
    role = models.IntegerField(choices=role_choice, default=0)
    avt = models.ImageField(null=True, blank=True)

NCKH-AHG/home/forms.py
from django import forms
import re 
from user.models import CustomerUser
from django.contrib.auth.models import Group, User
from django.core.exceptions import ObjectDoesNotExist
from django.forms.fields import ChoiceField
from django import forms
from django.core.files.images import get_image_dimensions
from django.forms import widgets

class RegisForm(forms.Form):
    username = forms.CharField(label='Tài khoản', max_length=30)
    email = forms.EmailField(label='Email')
    password1 = forms.CharField(label='Mật khẩu', widget=forms.PasswordInput())
    password2 = forms.CharField(label='Nhập lại mật khẩu', widget=forms.PasswordInput())
    def clean_password2(self):
        if 'password1' in self.cleaned_data:
            password1 = self.cleaned_data['password1']
            password2 = self.cleaned_data['password2']
            if password1 == password2 and password1:
                return password2
        raise forms.ValidationError("Mật khẩu không hợp lệ")
    def clean_username(self):
        username = self.cleaned_data['username']
        if re.search(r'^\w+&@!#$%* ', username):
            raise forms.ValidationError("Tên tài khoản có kí tự đặc biệt")
        try:
            CustomerUser.objects.get(username=username)
        except CustomerUser.DoesNotExist:
            return username
        raise forms.ValidationError("Tài khoản đã tồn tại")
    def save(self):
        CustomerUser.objects.create_user(username=self.cleaned_data['username'], email=self.cleaned_data['email'], password=self.cleaned_data['password1'])

#forms.py
class updateUser(forms.ModelForm):
    class Meta:
        model = CustomerUser
        fields = ('stt', 'lop', 'school', 'phone_number', 'email', 'first_name')

class roleUser(forms.ModelForm):
    class Meta:
        model = CustomerUser
        fields = ('role',)

NCKH-AHG/home/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import RegisForm, roleUser, updateUser
from django.shortcuts import redirect
import mysql.connector
from django.http import HttpResponse

# Create your views here.
def index(request):
    return render(request, 'pages/home.html')

def contact(request):
    return render(request, 'pages/contact.html')

def error(request, exception):
    return render(request, 'pages/error.html', {'message': exception})

def register(request):
    form = RegisForm()
    if request.method == 'POST':
        form = RegisForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/login/')
    return render(request, 'pages/register.html', {'form' : form})

def nopbai(request):
    return render(request, 'pages/nopbai.html')

def profile(request):
    mydb = mysql.connector.connect(
        host="localhost",
        user="khanghy1102",
        password="1102",
        database="DeadDB"
            )
            
    mycursor = mydb.cursor()
    sql1 = "SELECT * FROM `baitap_lophoc`"

    mycursor.execute(sql1)
    myresult1 = mycursor.fetchall()
    my_list1 = myresult1
    my_dict1 = dict() 
    for index,value1 in enumerate(my_list1):
        my_dict1[index] = value1
    context = {"q":my_dict1,}
    return render(request, 'pages/profile.html', context)

def add_profile(request):
    s = updateUser()
    context = {'f' : s}
    return render(request, 'pages/addprofile.html', context)

def update_profile(request):
    if request.method == "POST":
        u = updateUser(request.POST)
        if u.is_valid():
            mydb = mysql.connector.connect(
            host="localhost",
            user="khanghy1102",
            password="1102",
            database="DeadDB"
            )
                    
            mycursor = mydb.cursor()

            sql = "UPDATE user_customeruser SET stt = %s, lop = %s, school = %s, phone_number = %s, email = %s, first_name = %s WHERE username = %s"
            
            d_fn = request.POST.get('firstname','')
            d_stt = request.POST.get('stt', '')
            d_lop = request.POST.get('lop', '')
            d_school = request.POST.get('school', '')
            d_phonenumber = request.POST.get('phone_number', '')
            d_email = request.POST.get('email', '')
            d_user = request.POST.get('user', '')

            val = (d_stt, d_lop, d_school, d_phonenumber, d_email, d_fn, d_user)
            mycursor.execute(sql, val)
            mydb.commit()
            return render(request, 'pages/profile.html')
        else:
            return HttpResponse('<script>alert("Lỗi valid")</script>')
    else:
        return HttpResponse('<script>alert("Lỗi post")</script>')

def roleselect(request):
    return render(request, 'pages/roleselect.html')

def rolegv(request):
    if request.method == "POST":
        r = roleUser(request.POST)
        if r.is_valid():
            mydb = mysql.connector.connect(
            host="localhost",
            user="khanghy1102",
            password="1102",
            database="DeadDB"
            )
                    
            mycursor = mydb.cursor()
            
            sql = "UPDATE user_customeruser SET role = %s WHERE username = %s"
            
            d_role = request.POST.get('role', '')
            d_user = request.POST.get('user', '')

            val = (d_role, d_user)
            mycursor.execute(sql, val)
            mydb.commit()
            return render(request, 'pages/profile.html')
        else:
            return HttpResponse('<script>alert("Lỗi valid")</script>')
    else:
        return HttpResponse('<script>alert("Lỗi post")</script>')

NCKH-AHG/home/templates/pages/addprofile.html
{% extends "pages/base.html" %}
{% load static %}
{% block title %}Profile Editor{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/stylesprofile.css' %}">
<form method='POST' action='{% url "updateprofile" %}'>
    {% csrf_token %}
  <div class="wrapper">
    <div class="left">
      <img src="https://66.media.tumblr.com/1a1c3bcc08b5a048b90139a56fe7f415/tumblr_o9ku1rVS8z1vnqjx7o2_250.png" alt="user" width="100">
        <h4><strong>{{user.username}}</strong></h4>
          {% if user.role == 0 %}
            Học Sinh
          {% else %}
            Giáo Viên
          {% endif %}
    </div>
    <div class="right">
        <div class="info">
            <h3>Thông Tin Cá Nhân</h3>
              <div class="info_data">
                <div class="data">
                  <div class="form-group">
                    <label>Họ và Tên</label>
                    <input style=" 
                    background-color: #dddddd;
                    color: #666666;
                    padding: 10px 32px;
                    border: 2px solid transparent;
                    outline: none;
                    font-weight: 500;
                    font-size: 16px;
                    line-height: 1.4;
                    width: 100px;
                    height: 40px;
                    transition: all 0.2s;
                    width: 100%;
                    max-width: 100%;
                    min-width: 100%;
                    cursor: text;
                    background-color: #f3f3f3;
                    margin-top: 10px;
          "name='firstname' value='{{ user.first_name }}' type="firstname" maxlength="254" id="id_firstname" class="form-control form-control-lg" required></p>
                    <label>Email</label>
                    <input style=" 
                    background-color: #dddddd;
                    color: #666666;
                    padding: 10px 32px;
                    border: 2px solid transparent;
                    outline: none;
                    font-weight: 500;
                    font-size: 16px;
                    line-height: 1.4;
                    width: 100px;
                    height: 40px;
                    transition: all 0.2s;
                    width: 100%;
                    max-width: 100%;
                    min-width: 100%;
                    cursor: text;
                    background-color: #f3f3f3;
                    margin-top: 10px;
          "name='email' value='{{ user.email }}' type="email" maxlength="254" id="id_email" class="form-control form-control-lg"required></p>
                    <label>Số thứ tự</label>
		                <input style=" 
                    background-color: #dddddd;
                    color: #666666;
                    padding: 10px 32px;
                    border: 2px solid transparent;
                    outline: none;
                    font-weight: 500;
                    font-size: 16px;
                    line-height: 1.4;
                    width: 100px;
                    height: 40px;
                    transition: all 0.2s;
                    width: 100%;
                    max-width: 100%;
                    min-width: 100%;
                    cursor: text;
                    background-color: #f3f3f3;
                    margin-top: 10px;
          "name='stt' value='{{ user.stt }}' type="number" id="id_stt" class="form-control form-control-lg" required></p>
                    <label>Lớp</label>
		                <input style=" 
                    background-color: #dddddd;
                    color: #666666;
                    padding: 10px 32px;
                    border: 2px solid transparent;
                    outline: none;
                    font-weight: 500;
                    font-size: 16px;
                    line-height: 1.4;
                    width: 100px;
                    height: 40px;
                    transition: all 0.2s;
                    width: 100%;
                    max-width: 100%;
                    min-width: 100%;
                    cursor: text;
                    background-color: #f3f3f3;
                    margin-top: 10px;
          "name='lop' value='{{ user.lop }}' type="text" maxlength="20" id="id_lop" class="form-control form-control-lg" required></p>
                    <label>Trường</label>
		                <input style=" 
                    background-color: #dddddd;
                    color: #666666;
                    padding: 10px 32px;
                    border: 2px solid transparent;
                    outline: none;
                    font-weight: 500;
                    font-size: 16px;
                    line-height: 1.4;
                    width: 100px;
                    height: 40px;
                    transition: all 0.2s;
                    width: 100%;
                    max-width: 100%;
                    min-width: 100%;
                    cursor: text;
                    background-color: #f3f3f3;
                    margin-top: 10px;
          "name='school' value='{{ user.school }}' type="text" maxlength="30" id="id_school" class="form-control form-control-lg" required></p>
                    <label>Số điện thoại</label>
                    <input style=" 
                    background-color: #dddddd;
                    color: #666666;
                    padding: 10px 32px;
                    border: 2px solid transparent;
                    outline: none;
                    font-weight: 500;
                    font-size: 16px;
                    line-height: 1.4;
                    width: 100px;
                    height: 40px;
                    transition: all 0.2s;
                    width: 100%;
                    max-width: 100%;
                    min-width: 100%;
                    cursor: text;
                    background-color: #f3f3f3;
                    margin-top: 10px;
          "name="phone_number" value='{{ user.phone_number }}' type="text" maxlength="15" id="id_phone_number" class="form-control form-control-lg" required></p>
                    <input value='{{user.username}}' name='user' hidden>
                  <button class="button-36" role="button" type='submit'>Save</button>
              </div>
            </div>
          </div>
        </div>
      </div>
  </div>
</form>
</body>
</html>
{% endblock %}

NCKH-AHG/home/templates/pages/base.html
<!DOCTYPE html>
<html lang="vi" dir="ltr">
<head>
    
    <meta charset="UTF-8">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js" ></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.0.18/dist/sweetalert2.all.min.js"></script>
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style11.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/button1.css' %}" type="text/css">
    <link href='https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css' rel='stylesheet'>
    <meta name="viewport" content="width=device-width, initial-scales=1.0">
</head>
<body>
    <div class="sidebar">
        <div class="logo_content">
            <div class="logo">
                <i class='bx bxl-css3'></i>
                <div class="logo_name">  AHG</div>
            </div>
            <i class='bx bx-menu' id="btn"></i>
        </div>
        <ul class="nal_list">
            <li>
                <a href="/">
                <i class='bx bx-grid'></i>
                <span class="links_name">Trang Chủ</span>
                </a>
                <span class="tooltip">Trang Chủ</span>
            </li>
            <li>
                <a href="{% url 'profile' %}">
                <i class='bx bx-user' ></i>
                <span class="links_name">Người Dùng</span>
                </a>
                <span class="tooltip">Người Dùng</span>
            </li>
            <li>
                <a href="{% url 'baitap' %}">
                <i class='bx bxs-book-content' ></i>
                <span class="links_name">Bài Tập</span>
                </a>
                <span class="tooltip">Bài Tập</span>
            </li>
            <li>
                <a href="{% url 'contact' %}">
                <i class='bx bx-store' ></i>
                <span class="links_name">Cửa Hàng</span>
                </a>
                <span class="tooltip">Cửa Hàng</span>
            </li>
            <li>
                <a href="{% url 'contact' %}">
                <i class='bx bx-cog' ></i>
                <span class="links_name">Cài Đặt</span>
                </a>
                <span class="tooltip">Cài Đặt</span>
            </li>
        </ul>
    <div class="profile_content">
        <div class="profile">
            <div class="profile_details">
                <div class="name_job">
                    {% if user.username %}
                    <img src="{% static 'images/hey.png' %}">
                    <a href="{% url 'profile' %}"><span style="font-size: 3vh;
                        color: rgb(255, 255, 255);
                        text-decoration: none;
                        padding: 1vh 1vh 1vh 1vh;
                        height: 100vh;
                        padding-top: 50vh;
                        width: 50%;
                        vertical-align: text-bottom;
                        line-height: 2;
                        text-align: justify;"> {{user.username}}</span></a>
                    <a href="{% url 'logout' %}" class='bx bx-log-out' id="log_out"></a>
                    {% else %}
                    <button style='  align-items: center;
                    background-color: #3976d8;
                    border: 2px solid #3976d8;
                    box-sizing: border-box;
                    color: #fff;
                    cursor: pointer;
                    display: inline-flex;
                    fill: #000;
                    font-family: Inter,sans-serif;
                    font-size: 16px;
                    font-weight: 600;
                    height: 40px;
                    justify-content: center;
                    letter-spacing: -.8px;
                    line-height: 24px;
                    min-width: 100px;
                    padding: -17px 17px;
                    text-align: center;
                    text-decoration: none;
                    transition: all .3s;
                    user-select: none;
                    -webkit-user-select: none;
                    touch-action: manipulation;' onclick='window.location.href="{% url "register" %}"'><span>Đăng ký</span></button>  
                    <button class='button-81' style='  align-items: center;
                    background-color: #3976d8;
                    border: 2px solid #3976d8;
                    box-sizing: border-box;
                    color: #fff;
                    cursor: pointer;
                    display: inline-flex;
                    fill: #000;
                    font-family: Inter,sans-serif;
                    font-size: 16px;
                    font-weight: 600;
                    height: 40px;
                    justify-content: center;
                    letter-spacing: -.8px;
                    line-height: 24px;
                    min-width: 100px;
                    padding: -17px 17px;
                    text-align: center;
                    text-decoration: none;
                    transition: all .3s;
                    user-select: none;
                    -webkit-user-select: none;
                    touch-action: manipulation;' onclick='window.location.href="{% url "login" %}"'>Đăng nhập</button>
                    {% endif %}
                </div>
                </div>
            </div>
        </div>
    </div>
    <div class="home_content">
        
        <div class="text">
           {% block content %}
           {% endblock %}
           
        </div>
        <br/><center>
    </center>
    </div>

<script>
    let btn = document.querySelector("#btn");
    let sidebar = document.querySelector(".sidebar");

btn.onclick = function() {
    sidebar.classList.toggle("active");
}
</script>
</body>
</html>

NCKH-AHG/home/templates/pages/contact.html
{% extends "pages/base.html" %}

{% block title %}Contact{% endblock %}

{% block content %}
<head>
<center><p><h1><label><strong>AUTOMATE HISTORY GRADING</strong><label></h1></p></center>
</head>
<hr/>
<center><p style="color: red">Đang phát triển...</p></center>
<hr/>
{% endblock %}

NCKH-AHG/home/templates/pages/error.html
{% extends "pages/base.html" %}
 
{% block title %}Error{% endblock %}
 
{% block content %}
<head>
<center><p><h1><label><strong>AUTOMATE HISTORY GRADING</strong><label></h1></p></center>
</head>
<hr/>
<center><h2><strong>What are you doing?</strong></h2>
</center>
<hr/>
<center><img src="https://i.imgur.com/pg49Gbf.gif" alt="user" width="800"></center>
<center><i><label><h3>Tính hack server à?</h3></label></i></center>
{% endblock %}

NCKH-AHG/home/templates/pages/home.html
{% extends "pages/base.html" %}

{% block title %}AHG{% endblock %}

{% block content %}
<head>
{% load static %}
<link rel="stylesheet" href="{% static 'css/home.css' %}" type="text/css">
<link rel="stylesheet" href="{% static 'css/theme1.css' %}" type="text/css">
<link rel="stylesheet" href="{% static 'css/theme2.css' %}" type="text/css">
</head>
<body>
    <div class="hygay">
        <p>Copyright &copy; 2021 AUTOMATE HISTORY GRADING</p>
    </div>
    <section class="hero hero-bg d-flex justify-content-center align-items-center">
        <div class="container">
             <div class="row">
                 <div class="col-lg-6 col-md-10 col-12 d-flex flex-column justify-content-center align-items-center">
                       <div class="hero-text">
                            
                            {% if user.username %}
                            <h1 class="text-white" id="left"  data-aos="fade-up">Chào mừng bạn trở lại</br> với hệ thống</h1>
                              {% if user.role == 0 %}
                              <a href="{% url 'baitap' %}" class="custom-btn btn-bg btn mt-3" id="left">Vào làm bài tập!</a>
                              {% else %}
                              <a href="{% url 'baitap' %}" class="custom-btn btn-bg btn mt-3" id="left">Vào xem điểm và quản lý bài kiểm tra!</a>
                              {% endif %}
                            {% else %}
                            <h1 class="text-white" id="left"  data-aos="fade-up">Chào mừng bạn đã đến với</br> với hệ thống</h1>
                            <a href="{% url "login" %}" class="custom-btn btn-bg btn mt-3" id="left">Vui lòng đăng nhập để biết thêm thông tin chi tiết</a>
                            {% endif %}
                       </div>
                      </div>
                 <div class="col-lg-6 col-12">
                   <div class="hero-image" >
                     <img src="images/working-girl.png" class="img-fluid" alt="">
                   </div>
                 </div>

             </div>
        </div>
</section>
    {% endblock %}
</body>

NCKH-AHG/home/templates/pages/login.html
<!DOCTYPE html>
<html lang="en">
    <head>
    {% load static %} 
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.0.18/dist/sweetalert2.all.min.js"></script>
        <link rel="stylesheet" href="{% static 'css/register.css' %}" type="text/css">
        <link href='https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css' rel='stylesheet'>
        <title>Đăng Nhập</title>
    </head>
    <body>
        <div class="nav">
            <div class="card">
                <form method="POST">
                {% csrf_token %}
                <h2>ĐĂNG NHẬP</h2> 
                {{ form.role }}
                {% for key, value in form.errors.items %}
                {{value}}
                {% endfor %}
                <p><label>Tên Đăng Nhập </label><input type="text" name="username" autofocus autocapitalize="none" autocomplete="username" maxlength="150" required id="id_username"></p>
                <p><label>Mật Khẩu </label><input type="password" name="password" autocomplete="current-password" required id="id_password"></p>
                <input type="hidden" name="next" value="/"/>
                <input class="btn btn-success" type="submit" value="Đăng nhập"/> 
                <p class="new">Chưa có tài khoản? <a href="{% url 'register' %}">Đăng ký</a></p>
                <p class="new">Quay trở lại trang chủ? <a href="/">Quay lại</a></p>
                <div class="signin">
                    <h3>Hoặc Đăng Nhập Bằng</h3>
                    <ul class="linkk">
                        <li><img src="{% static 'images/fb.png' %}"></li>
                    </ul>
                </div>
            </div>
        </div>
    </form>
    <script type="text/javascript">
	$(document).ready(function() {
				$("#login1").click(function(){
				var username1 = $("[name=username]").val();
				var password1 = $("[name=password]").val();
			if (username1 == "" || password1 == "" ) {
			Swal.fire({ icon: 'warning', title: 'Thiếu Thông Tin', text: 'Vui lòng điền đầy đủ thông tin!', background: '#fff url(https://www.pngitem.com/pimgs/b/149-1492667_white-background-png.png)'})
		    return;
			}
		     else {
        		$("#login1").submit(function() {
				})
        	}
		})
	})
</script>
    </body>
</html>

NCKH-AHG/home/templates/pages/profile.html
{% extends "pages/base.html" %}
{% load static %} 
{% block title %}Profile{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/stylesprofile.css' %}">

{% if user.username %}
    <div class="wrapper">
    <div class="left">
              <img src="https://66.media.tumblr.com/1a1c3bcc08b5a048b90139a56fe7f415/tumblr_o9ku1rVS8z1vnqjx7o2_250.png" alt="user" width="100">
              <h4><strong>{{user.username}}</strong></h4>
                {% if user.role == 0 %}
                Học Sinh
                {% else %}
                Giáo Viên
                {% endif %}
                {% if user.school == '' %}
                <button class="button-36" role="button" onclick='window.location.href="{% url "addprofile" %}"'>Thêm Thông Tin</button>
                {% else %}
                <button class="button-36" role="button" onclick='window.location.href="{% url "addprofile" %}"'>Thay Đổi Thông Tin</button>
                {% endif %}       
    </div>
    <div class="right">
        <div class="info">
            <h3>Thông Tin Cá Nhân</h3>
              <div class="info_data">
                <div class="data">
                  <label>Họ Và Tên</label>
                  <p>{{user.first_name}}</p>
                  <label>Email</label>
                  <p>{{user.email}}</p>
                  <label>Số Thứ Tự</label>
                  <p>{{user.stt}}</p>
                  <label>Lớp</label>
                  {% for a, x in q.items %}
                  <p>{{x.1}}</p>
                  {% endfor %}
                  <label>Trường</label>
                  <p>{{user.school}}</p>
                  <label>Số Điện Thoại</label>
                  <p>{{user.phone_number}}</p>
                  <button onclick='window.location.href="/roleselect/"'style="
        
        
                  appearance: none;
                  background-color: #FAFBFC;
                  border: 1px solid rgba(27, 31, 35, 0.15);
                  border-radius: 6px;
                  box-shadow: rgba(27, 31, 35, 0.04) 0 1px 0, rgba(255, 255, 255, 0.25) 0 1px 0 inset;
                  box-sizing: border-box;
                  color: #24292E;
                  cursor: pointer;
                  font-size: 14px;
                  font-weight: 500;
                  line-height: 20px;
                  list-style: none;
                  padding: 6px 16px;
                  position: relative;
                  transition: background-color 0.2s cubic-bezier(0.3, 0, 0.5, 1);
                  user-select: none;
                  -webkit-user-select: none;
                  touch-action: manipulation;
                  vertical-align: middle;
                  white-space: nowrap;
                  word-wrap: break-word;
                  width: 33%;
                  margin-bottom: 50px;
          
          
                  ">Thay đổi vị trí</button>
                </div>
              </div>
        </div>
      </div>
  </div>
</body>
</html>

{% else %}
<center><p><h1><label><strong>AUTOMATE HISTORY GRADING</strong><label></h1></p></center><br/>
<hr/>
    <h3><center><p>Vui lòng <a href="{% url 'login' %}">đăng nhập</a> để có quyền truy cập vào trang!</p></center></h3><hr/>
{% endif %}
{% endblock %}

NCKH-AHG/home/templates/pages/register.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}    
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/looogin.css' %}" type="text/css">
    <link href='https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css' rel='stylesheet'>
    <title>Đăng Kí</title>
</head>
<body>
    <div class="nav">
        <div class="card">
            <div>
                {% csrf_token %}
                <form method='POST' action="{% url 'register' %}">
                {% csrf_token %}
                <h2>ĐĂNG KÝ</h2>
                <p><label>Tài khoản </label><input type="text" name="username" maxlength="30" required id="id_username"></p>
                <p><label>Emai </label><input type="email" name="email" required id="id_email"></p>
                <p><label>Mật khẩu </label><input type="password" name="password1" required id="id_password1"></p>
                <p><label>Nhập lại Mật khẩu </label><input type="password" name="password2" required id="id_password2"></p>  
                <input class='btn btn-success' type="submit" value="ĐĂNG KÝ"/>
                <p class="new">Đã có tài khoản? <a href="{% url 'login' %}">Đăng nhập</a></p>
                <p class="new">Quay trở lại trang chủ? <a href="/">Quay lại</a></p>
                <div class="signin">
                    <h3>Hoặc Đăng Ký Bằng</h3>
                    <ul class="linkk">
                         <li><img src="{% static 'images/fb.png' %}"></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div>  
    </div>
</body>
</html>

NCKH-AHG/home/templates/pages/roleselect.html
{% extends "pages/base.html" %}
{% load static %}
{% block title %}role{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/stylesprofile.css' %}">
<form method='POST' action='{% url "rolegv" %}'>
    {% csrf_token %}
  <div class="wrapper">
    <div class="left">
      <img src="https://66.media.tumblr.com/1a1c3bcc08b5a048b90139a56fe7f415/tumblr_o9ku1rVS8z1vnqjx7o2_250.png" alt="user" width="100">
        <h4><strong>{{user.username}}</strong></h4>
          {% if user.role == 0 %}
            Học Sinh
          {% else %}
            Giáo Viên
          {% endif %}
    </div>
    <div class="right">
        <div class="info">
            <h3>Thông Tin Cá Nhân</h3>
              <div class="info_data">
                <div class="data">
                  <div class="form-group">
                    <input value='{{user.username}}' name='user' hidden><br/>
                    <input type='radio' name='role' value='0'> Học Sinh<br/>
                    <input type='radio' name='role' value='1'> Gíao Viên<br/>
                    <button class="button-36" role="button" type='submit'>Xác Nhận</button>
              </div>
            </div>
          </div>
        </div>
      </div>
  </div>
</form>
</body>
</html>
{% endblock %}