NCKH-AHG/PythonWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('baitap/', include('baitap.urls'))
]
handler404 = 'home.views.error'

NCKH-AHG/baitap/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.BTListView.as_view(), name='baitap'),
  path('<int:id>/', views.questionlist, name='quesview'),
  path('save/<int:id>/', views.save_nopbai, name='save'),
  path('deleteex/<int:id>/',views.exdelconf, name='delexam'),
  path('deleteques/<int:id>/',views.quesdelconf, name='delques'),
  path('deleteans/<int:id>/',views.ansdelconf, name='deleteans'),
  path('deleteyes/', views.examdelete, name='examdelete'),
  path('deletequesyes/', views.deleteques, name='deleteques'),
  path('deleteansyes/', views.ansdelete, name='deleteansyes'),
  path('thembai/', views.them_bai, name='thembai'),
  path('themlop/', views.them_lop, name='themlop'),
  path('savelop/', views.save_lop, name='savelop'),
  path('saveex/', views.save_exam, name='saveex'),
  path('saveques/', views.savecauhoi, name='saveques'),
  path('quesedit/<int:qid>/', views.addkey, name='keyword'),
  path('viewdiem/<int:uid>/', views.viewdiem, name='viewdiem'),
  path('editques/', views.editques, name='editques'),
  path('editexam/<int:id>/', views.editexam, name='editexam'),
  path('saveeditexam/<int:id>/', views.saveeditexam, name='saveeditexam'),
  path('profileshow/<int:id>/', views.profileshow, name='profileshow'),
]

NCKH-AHG/home/urls.py
from django.urls import path
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
   path('', views.index, name='index'),
   path('profile/', views.profile, name='profile'),
   path('contact/', views.contact, name='contact'),
   path('register', views.register, name="register"),
   path('login/',auth_views.LoginView.as_view(template_name="pages/login.html"), name="login"),
   path('logout/',auth_views.LogoutView.as_view(next_page='/'),name='logout'),
   path('nopbai/', views.nopbai, name='nopbai'),
   path('update/', views.add_profile, name='addprofile'),
   path('updateprofile/', views.update_profile, name='updateprofile'),
   path('rolegv/', views.rolegv, name='rolegv'),
   path('roleselect/', views.roleselect, name='roleselect'),
]

NCKH-AHG/baitap/models.py
import abc
from django.db import models
from django.conf import settings
import re
from django.db.models.deletion import CASCADE
from django.db.models.base import Model
from django.db.models.fields import DateField, SlugField
from django.db.models.fields.related import ForeignKey
from django.utils.translation import templatize 
from user.models import CustomerUser
from django.contrib.auth.models import AbstractUser


# Create your models here.

class exam_exam(models.Model):
    eid = models.AutoField(primary_key=True)
    uid = models.ForeignKey(CustomerUser, on_delete=CASCADE)
    max_point = models.FloatField(default=10)
    title = models.CharField(default='', max_length=300)
    description = models.TextField(max_length=700)
    start_time = models.CharField(max_length=20)
    end_time = models.CharField(max_length=20)
    take = models.IntegerField(default=3)
    time = models.TimeField(default=0)
    code = models.IntegerField(default=0)
    create = models.DateTimeField(auto_now_add=True)


class exam_question(models.Model):
    qid = models.AutoField(primary_key=True)
    eid = models.ForeignKey(exam_exam, on_delete=CASCADE)
    max_point = models.FloatField(default=0)
    title = models.CharField(default='', max_length=300)
    description = models.CharField(default='', max_length=500)
    answergv = models.TextField(default='', blank=True, max_length=700)
    cauhoi = models.IntegerField(default=1, blank=False)
    key = models.TextField(default='')
    # def __str__(self):
        #return self.eid


class lophoc(models.Model):
    cid = models.AutoField(primary_key=True)
    lophoc = models.CharField(default='', max_length=50)
    sohocsinh = models.IntegerField(default=0)
    lop = models.IntegerField(default=0)
    uid = models.ForeignKey(CustomerUser, on_delete=CASCADE)

class lophocbehind(models.Model):
    lophocso = models.IntegerField(default=0)


class exam_answerkey(models.Model):
    kid = models.AutoField(primary_key=True)
    qid = models.ForeignKey(exam_question, on_delete=CASCADE)
    key = models.TextField(default='')

class exam_primarykey(models.Model):
    pkid = models.AutoField(primary_key=True)
    kid = models.ForeignKey(exam_answerkey, on_delete=CASCADE)
    point = models.FloatField(default=0)
    pkey = models.TextField(default='')


class exam_answer(models.Model):
    aid = models.AutoField(primary_key=True)
    qid = models.ForeignKey(exam_question, on_delete=CASCADE)
    uid = models.ForeignKey(CustomerUser, on_delete=CASCADE)
    answer = models.CharField(default='', max_length=700)
    point = models.FloatField(default=0)
    create = models.DateTimeField(auto_now_add=True)

NCKH-AHG/baitap/forms.py
from django import forms
from django.forms import fields, widgets
from . models import exam_answer, exam_exam, exam_question, exam_answerkey, lophoc


#class nopbai(forms.ModelForm):
#    class Meta:
#        model = exam_answer
#        fields = ('answer', 'qid', 'uid',)
#        widgets = {
#            'answer': widgets.Textarea(attrs={'id':'noidung', 'cols':'100'}),
#        }


class thembai(forms.ModelForm):
    class Meta:
        model = exam_exam
        fields = ('title','description','take','max_point','code','uid', 'start_time', 'end_time', 'time')
        widgets = {
            'title': widgets.Input(attrs={'id':'title'}),
            'description': widgets.Textarea(attrs={'id':'description'}),
            'max_point': widgets.Input(attrs={'id':'max_point'}),
            'take': widgets.Input(attrs={'id':'take'}),
            'code': widgets.Input(attrs={'id':'code'}),
            'uid': widgets.Input(attrs={'id':'uid'}),
            'start_time': widgets.Input(attrs={'id':'st'}),
            'end_time': widgets.Input(attrs={'id':'et'}),
            'time': widgets.Input(attrs={'name':'time', 'id':'time'}),
        }



class themlop(forms.ModelForm):
    class Meta:
        model = lophoc
        fields = ('lophoc','sohocsinh',)
        widgets = {
            'lophoc': widgets.Input(attrs={'id':'lophoc'}),
            'sohocsinh': widgets.Textarea(attrs={'id':'sohocsinh'}),
        }



class addcauhoi(forms.ModelForm):
    class Meta:
        model = exam_question
        fields = ('max_point', 'title', 'description', 'eid', 'cauhoi', 'answergv',)
        widgets = {
            'title': widgets.Input(attrs={'id':'title', 'cols':'100', 'rows':"10"}),
            'description': widgets.Textarea(attrs={'id':'description', 'cols':'100'}),
            'max_point': widgets.Input(attrs={'id':'max_point'}),
            'eid': widgets.Input(attrs={'id':'eid'}),
            'cauhoi': widgets.Input(attrs={'id':'cauhoi'}),
            'answergv': widgets.Input(attrs={'id':'answergv'}),
        }


class deleteques(forms.ModelForm):
    class meta:
        model = exam_question
        fields = ('qid',)
        widgets = {
            'qid': widgets.Input(attrs={'id': 'qid'})
        }


class quesedit(forms.ModelForm):
    class Meta:
        model = exam_question
        fields = ('max_point', 'title', 'description', 'answergv', 'cauhoi','key',)


class addkeyword(forms.ModelForm):
    class meta:
        model = exam_answerkey
        fields = ('key', 'qid',)
        widgets = {
            'key': widgets.Input(attrs={'id': 'key'}),
            'qid': widgets.Input(attrs={'id': 'qid'})
        }



    

NCKH-AHG/baitap/views.py
from os import pardir
from typing import List
from django import http
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from numpy import add, where
from . models import exam_exam, exam_question
from django.views.generic import ListView, DetailView
from django.http import HttpResponse
from . forms import addkeyword, quesedit, thembai, addcauhoi, deleteques, themlop
from . import Scoring, tfidf
from django.shortcuts import redirect
import mysql.connector
import datetime
import json
import underthesea
from underthesea import word_tokenize, pos_tag
import logging    # first of all import the module

logging.basicConfig(filename='std.log', filemode='w', format='%(name)s - %(levelname)s - %(message)s')
logging.warning('This message will get logged on to a file')

#Show Bài Tập
class BTListView(ListView):
    queryset = exam_exam.objects.all().order_by('-eid')
    template_name = 'baitap/baitap.html'
    context_object_name = 'baitapp'
    paginate_by = 3
class BTDetailView(DetailView):
    model = exam_question
    template_name = 'baitap/baitap.html'
#Show Câu Hỏi
def questionlist(request, id):
    #kết nối đến DB (Để thông tin giống như ở Django DB/Admin)

    mydb = mysql.connector.connect(
        host="localhost",
        user="khanghy1102",
        password="1102",
        database="DeadDB"
        )     
    mycursor1 = mydb.cursor()
    #maxpoint
    sql1 = "SELECT * FROM `baitap_exam_question` WHERE eid_id='%s'"
    val = (id,)
    mycursor1.execute(sql1, val)
    myresult1 = mycursor1.fetchall()

    #myArray = JSON.Parse(context)
    sql = "SELECT * FROM `baitap_exam_exam` WHERE eid='%s'"
    val = (id,)
    mycursor1.execute(sql, val)
    myresult2 = mycursor1.fetchall()

    my_list1 = myresult2
    my_dict1 = dict() 
    for index,value1 in enumerate(my_list1):
        my_dict1[index] = value1

    if myresult1 == '':
        my_dict = ''
    
    else:
        my_list = myresult1
        my_dict = dict() 
        for index,value in enumerate(my_list):
            my_dict[index] = value
    s = addcauhoi()
    context = {'eid': id, 's': my_dict, 'f': my_dict1, 'b': myresult1, 'u':s}
    return render(request, 'baitap/quesview.html', context)
#Lưu Câu Hỏi
def savecauhoi(request):
    if request.method == "POST":
        #kết nối đến DB (Để thông tin giống như ở Django DB/Admin)
        mydb = mysql.connector.connect(
            host="localhost",
            user="khanghy1102",
            password="1102",
            database="DeadDB"
            )
        
        mycursor = mydb.cursor()

        #biến sql chứa lệnh cần thực thi
        sql = "INSERT INTO baitap_exam_question (max_point, title, description, eid_id, answergv, cauhoi, `key`) VALUES (%s, %s, %s, %s, %s, %s, %s)"
        #sql = "INSERT INTO tên_bảng (giá_trị_1, giá_trị_2, ... , giá_trị_N) VALUES (%s, %s, ..., %s)"
        #data cần catch khi request đến
        d_maxpoint = request.POST.get('max_point', '')
        d_title = request.POST.get('title', '')
        d_description = request.POST.get('description', '')
        d_eid = request.POST.get('eid', '')
        d_answer = request.POST.get('answergv', '')
        d_cauhoi = request.POST.get('cauhoi', '')
        d_key = request.POST.get('key', '')
        
        #data cần push lên DB, mỗi giá trị/biến tương ứng với %s ở lệnh trong biến sql ở trên
        val = (d_maxpoint, d_title, d_description, d_eid, d_answer, d_cauhoi, str(d_key))
        mycursor.execute(sql, val)
        mydb.commit()
        
        next = request.POST.get('next', '/')
        return HttpResponseRedirect(next)
    else:
        return HttpResponse('<script>alert("Lỗi post")</script>')
#Edit câu hỏi
def addkey(request, qid):
    mydb = mysql.connector.connect(
        host="localhost",
        user="khanghy1102",
        password="1102",
        database="DeadDB"
            )
            
    mycursor = mydb.cursor()
    sql1 = "SELECT * FROM `baitap_exam_question` WHERE qid='%s'"
    val = (qid,)
    mycursor.execute(sql1, val)
    myresult1 = mycursor.fetchall()
    my_list1 = myresult1
    my_dict1 = dict() 
    for index,value1 in enumerate(my_list1):
        my_dict1[index] = value1
    s = quesedit()
    context = {"qid":qid, "q":my_dict1, "s":s}
    return render(request, 'baitap/quesedit.html', context)
#Lưu edit câu hỏi
def savekeyword(request):
    if request.method == "POST":
        b = quesedit(request.POST)
        if b.is_valid():
            mydb = mysql.connector.connect(
                host="localhost",
                user="khanghy1102",
                password="1102",
                database="DeadDB"
                )
            
            mycursor = mydb.cursor()

            sql = "UPDATE baitap_exam_question SET max_point = %s, title = %s, description = %s, answergv = %s, cauhoi = %s, `key` = %s WHERE qid = %s"
            d_maxpoint = request.POST.get('max_point', '')
            d_title = request.POST.get('title', '')
            d_description = request.POST.get('description', '')
            d_answer = request.POST.get('answergv', '')
            d_cauhoi = request.POST.get('cauhoi', '')
            d_key = request.POST.get('keyword', '')
            d_qid = request.POST.get('qid', '')
            
            #data cần push lên DB, mỗi giá trị/biến tương ứng với %s ở lệnh trong biến sql ở trên
            val = (d_maxpoint, d_title, d_description, d_answer, d_cauhoi, str(d_key), d_qid)
            mycursor.execute(sql, val)
            mydb.commit()
            return HttpResponseRedirect('/editdone/')
        else:
            return HttpResponse('<script>alert("Lỗi valid")</script>')
    else:
        return HttpResponse('<script>alert("Lỗi post")</script>')


#Xoá Câu Hỏi
def quesdelconf(request, id):
    eid = request.POST.get('eid', '')
    return render(request, 'baitap/delexam.html', {'id':id, 'eid': eid})
def deleteques(request):
    s = addcauhoi()
    mydb = mysql.connector.connect(
        host="localhost",
        user="khanghy1102",
        password="1102",
        database="DeadDB"
        )

    mycursor = mydb.cursor()

            #biến sql chứa lệnh cần thực thi
    sql = "DELETE FROM baitap_exam_question WHERE `qid` = %s"
    d_id = request.POST.get('qid', '')
    val = (d_id,)
    mycursor.execute(sql, val)
    mydb.commit()
    eid = request.POST.get('eid', '')
    return HttpResponseRedirect('/baitap/%s/' %eid)
    

#Xoá Bài KT
def exdelconf(request, id):
    return render(request, 'baitap/delques.html', {'id':id})
def examdelete(request):
    s = thembai()
    mydb = mysql.connector.connect(
        host="localhost",
        user="khanghy1102",
        password="1102",
        database="DeadDB"
        )

    mycursor = mydb.cursor()

            #biến sql chứa lệnh cần thực thi
    sql = "DELETE FROM baitap_exam_exam WHERE `eid` = %s"
    d_id = request.POST.get('eid','')
    val = (d_id,)
    mycursor.execute(sql, val)

    mydb.commit()
    #myArray = JSON.Parse(context)
    
    return HttpResponseRedirect('/baitap/')
#Lưu và Chấm Bài
def save_nopbai(request, id):
    if request.method == "POST":
        mydb = mysql.connector.connect(
            host="localhost",
            user="khanghy1102",
            password="1102",
            database="DeadDB"
            )
        mycursor = mydb.cursor()
        
        sql = "SELECT * FROM `baitap_exam_question` WHERE eid_id=%s"
        val = (id,)
        mycursor.execute(sql, val)
        myresult = mycursor.fetchall()
        for tupl1 in myresult:
            x = []
            for y in tupl1:
                x.append(y)
            MACAUHOI = x[0]
            DAPAN = x[5]
            CAUTRALOi = request.POST.get('answer','')
            input1 = DAPAN
            input2 = CAUTRALOi
            sql2 = "SELECT `key` FROM baitap_exam_question WHERE qid = %s"
            val = (MACAUHOI,)
            mycursor.execute(sql2, val) 
            myresult3 = mycursor.fetchall()
            def convertTuple(tup):
                str = ''
                for item in tup:
                    if item == None:
                        pass
                    else:
                        str = str + item
                return str
            def listToString(s): 
                str1 = ""  
                for ele in s: 
                    str1 += ele   
                return str1 
            for z in myresult3:
                a = convertTuple(z)
                list = pos_tag(a)
                maxdem = 0
                dem = 0
                for bac in list:
                    ronglist = []
                    chu = bac[0]
                    loai = bac[1]
                    if loai == "CH" or loai == "C":
                        pass
                    elif loai != "CH" and loai != "C":
                        ronglist.append(bac[0])
                        maxdem += 1
                        pui = listToString(ronglist)
                        so = pui.lower()
                        sanh = input2.lower()
                        if so in sanh:
                            dem += 1
                input_1 = input1
                input_2 = input2
                print(input_1, input_2)
                modelVersion = 0 
                model = Scoring.MakeModel(0)
                POINT = Scoring.similarity(model, input_1, input_2)*10
                LastPoint = (dem/maxdem)*2 + POINT*0.8
                Key = (dem/maxdem)*2
                UpPointAI = round(POINT, 2)
                UpKey = round(Key, 2)
                UpPoint = round(LastPoint, 2)
                if myresult3 == '':
                    UpPoint = UpPointAI
                    UpKey = ''
                sql = "INSERT INTO baitap_exam_answer (answer, point, pointai, pointkey, qid_id, uid_id, `create`) VALUES (%s, %s, %s, %s, %s, %s, %s)"
                d_create = datetime.datetime.now()
                d_ques = MACAUHOI
                d_user = request.POST.get('uid', '')

NCKH-AHG/baitap/templates/baitap/delans.html
{% extends "pages/base.html" %}

{% block title %}Confirmation{% endblock %}

{% block content %}
{% load static %}
    <link rel="stylesheet" href="{% static 'css/delete.css' %}">
<br/>
<hr/>
<center><h1><strong><p style='color: red'>Bạn có chắc chắn sẽ xoá? (Tác vụ này sẽ không thể hoàn tác)<p></strong></h1></center>
<hr/>
<center>
    <form method='POST' action="{% url 'deleteansyes' %}">
        {% csrf_token %}<br/>
<input value='{{qid}}' name='qid' id='qid' hidden>
<input value='{{id}}' name='aid' id='aid' hidden>
<input class='xoabut' value="Delete" type='submit'>
<input type=button class='viewbut' value="Back" onClick="reload_page()">
</center>
</form>
<script>
    function reload_page(){
        history.back();
    }
</script>
{% endblock %}

NCKH-AHG/baitap/templates/baitap/nopbai.html
{% extends "pages/base.html" %}

{% block title %}Nộp Bài{% endblock %}

{% block content %}
<head>
<center><p><h1><label><strong>AUTOMATE HISTORY GRADING</strong><label></h1></p></center>
</head>
<script type="text/javascript" src="http://js.nicedit.com/nicEdit-latest.js"></script>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.0.18/dist/sweetalert2.all.min.js"></script>
<form action="{% url 'save' %}" method="POST">
    {% csrf_token %}
	
	<p><strong><h2>{{ user.username }}</h2></strong></p>
    Bài làm:<br/>{{ f.answer }}<br/>
	<input type="number" name="point" value="0" step="any" id="id_point" hidden>
	<button class="btn btn-success" id="login1" name="login1" type='submit'>Nộp Bài</button> 
	<input value='1' name='qid' hidden><br/>
	<input value='{{ user.uid }}' name='uid'hidden><br/>
    
</form>
<script type="text/javascript">
bkLib.onDomLoaded(function() {
             new nicEditor().panelInstance('nsoidung');
        }); // Thay thế text area có id là area1 trở thành WYSIWYG editor sử dụng nicEditor
    $(document).ready(function() {
				$("#login1").click(function(){
				var name = $("[name=name]").val();
                var body = $("[name=body]").val();
			if (name == "" || body == "" ) {
			Swal.fire({ icon: 'warning', title: 'Thiếu thông tin', text: 'Vui lòng điền đầy đủ thông tin', background: '#fff url(https://www.pngitem.com/pimgs/b/149-1492667_white-background-png.png)'})
		    return;
			} else {
        		$("#login1").submit(function() {
				})
        	}
		})
	})
</script>
{% endblock %}

NCKH-AHG/baitap/templates/baitap/quesedit.html
{% extends "pages/base.html" %}
{% load static %}
{% block title %}Chỉnh Sửa Câu Hỏi{% endblock %}

{% block content %}
<head>
    <link rel="stylesheet" href="{% static 'css/thembai.css' %}">
    <script type="text/javascript" src="http://js.nicedit.com/nicEdit-latest.js"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.0.18/dist/sweetalert2.all.min.js"></script>
<center><p><h1><label><strong>AUTOMATE HISTORY GRADING</strong><label></h1></p></center>
</head>
<form id='theForm' method='POST' action="{% url 'editques' %}">
{% csrf_token %}
{% for a, x in q.items %}
<div style="margin-left: 12%; max-width: 76%">
<h2>Chỉnh Sửa Câu Hỏi</h2>
        <label>Câu số:</label><br/>
            <input style=" 
            background-color: #dddddd;
            color: #666666;
            padding: 10px 32px;
            border: 2px solid transparent;
            outline: none;
            font-weight: 500;
            font-size: 16px;
            line-height: 1.4;
            width: 100px;
            height: 50px;
            transition: all 0.2s;
            width: 100%;
            max-width: 100%;
            min-width: 100%;
            cursor: text;
            background-color: #f3f3f3;
            margin-top: 10px;
  " type="number" name="cauhoi" value="{{x.6}}" required id="id_cauhoi"><br/>
        <label>Câu Hỏi:</label><br/>
            <input style=" 
            background-color: #dddddd;
            color: #666666;
            padding: 10px 32px;
            border: 2px solid transparent;
            outline: none;
            font-weight: 500;
            font-size: 16px;
            line-height: 1.4;
            width: 100px;
            height: 50px;
            transition: all 0.2s;
            width: 100%;
            max-width: 100%;
            min-width: 100%;
            cursor: text;
            background-color: #f3f3f3;
            margin-top: 10px;
  "type="text" name="title" maxlength="300" value='{{x.2}}' required id="id_title"><br/>
        <label>Số Điểm: </label><br/>
            <input style=" 
            background-color: #dddddd;
            color: #666666;
            padding: 10px 32px;
            border: 2px solid transparent;
            outline: none;
            font-weight: 500;
            font-size: 16px;
            line-height: 1.4;
            width: 100px;
            height: 50px;
            transition: all 0.2s;
            width: 100%;
            max-width: 100%;
            min-width: 100%;
            cursor: text;
            background-color: #f3f3f3;
            margin-top: 10px;
  "type="number" name="max_point" value="{{x.1}}" step="any" required id="id_max_point"><br/>
        <label>Thông tin:</label><br/>
            <input style=" 
            background-color: #dddddd;
            color: #666666;
            padding: 10px 32px;
            border: 2px solid transparent;
            outline: none;
            font-weight: 500;
            font-size: 16px;
            line-height: 1.4;
            width: 100px;
            height: 50px;
            transition: all 0.2s;
            width: 100%;
            max-width: 100%;
            min-width: 100%;
            cursor: text;
            background-color: #f3f3f3;
            margin-top: 10px;
  "type="text" name="description" maxlength="500" value='{{x.3}}' required id="id_description"><br/>
        <label>Đáp án:</label><br/>
            <textarea style=" 
            background-color: #dddddd;
            color: #666666;
            padding: 10px 32px;
            border: 2px solid transparent;
            outline: none;
            font-weight: 500;
            font-size: 16px;
            line-height: 1.4;
            width: 100px;
            height: 150px;
            transition: all 0.2s;
            width: 100%;
            max-width: 100%;
            min-width: 100%;
            cursor: text;
            background-color: #f3f3f3;
            margin-top: 10px;
  "name="answergv" cols="40" rows="50" maxlength="700" id="id_answergv">{{x.5}}</textarea><br/>
        <label>Keyword</label><br/>
            <input style=" 
            background-color: #dddddd;
            color: #666666;
            padding: 10px 32px;
            border: 2px solid transparent;
            outline: none;
            font-weight: 500;
            font-size: 16px;
            line-height: 1.4;
            width: 100px;
            height: 50px;
            transition: all 0.2s;
            width: 100%;
            max-width: 100%;
            min-width: 100%;
            cursor: text;
            background-color: #f3f3f3;
            margin-top: 10px;
  "name="key" cols="40" rows="10" value='{{x.7}}' required id="id_key"><br/> 
            <input type="number" name="qid1" id="qid1" value='{{x.0}}' required hidden>
            <input type="number" name="eid1" id="eid1" value='{{x.4}}' required hidden>
        <button type='button' id='login1' name='login1' style="
        align-items: center;
        background-color: #81d4d2;
        border: 2px solid #81d4d2;
        box-sizing: border-box;
        color: #fff;
        cursor: pointer;
        display: inline-flex;
        fill: #000;
        font-family: Inter,sans-serif;
        font-size: 16px;
        font-weight: 600;
        height: 48px;
        justify-content: center;
        letter-spacing: -.8px;
        line-height: 24px;
        min-width: 140px;
        outline: 0;
        padding: 0 12px;
        text-align: center;
        user-select: none;
        -webkit-user-select: none;
        touch-action: manipulation;
        border-radius: 5px;
        margin-left: 1.2%;
        margin-top: 50px">Save</button>
        <input type=button value="Back" onClick="javascript:history.go(-1);" style="
        align-items: center;
        background-color: #81d4d2;
        border: 2px solid #81d4d2;
        box-sizing: border-box;
        color: #fff;
        cursor: pointer;
        display: inline-flex;
        fill: #000;
        font-family: Inter,sans-serif;
        font-size: 16px;
        font-weight: 600;
        height: 48px;
        justify-content: center;
        letter-spacing: -.8px;
        line-height: 24px;
        min-width: 140px;
        outline: 0;
        padding: 0 12px;
        text-align: center;
        user-select: none;
        -webkit-user-select: none;
        touch-action: manipulation;
        border-radius: 5px;
        margin-left: 1.2%;
        margin-top: 50px">
</div>
</form>
{% endfor %}
<script type="text/javascript">
    $(document).ready(function() {
				$("#login1").click(function(){
				var name1 = $("[name=title]").val();
				var name2 = $("[name=description]").val();
				var name3 = $("[name=max_point]").val();
				var name4 = $("[name=answergv]").val();
				var name5 = $("[name=key]").val();
			if (name1 == "" || name2 == "" || name3 == "" || name4 == "" || name5 == "") {
				Swal.fire({ icon: 'warning', title: 'Thiếu thông tin', text: 'Vui lòng điền đầy đủ thông tin', background: '#fff url(https://www.pngitem.com/pimgs/b/149-1492667_white-background-png.png)'})
		    	return;
			} else {
        		document.getElementById('theForm').submit()
        	}
		})
	})
</script>
{% endblock %}